
--MIRANDA

INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983245688','Castelo','Castelo.CA',NULL,'Castelo@gmail.com',250112);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983567688','Polar','Empresas Polar.CA',NULL,'EmpresasPolar@gmail.com',250113);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983579088','Confort','Confort.CA',NULL,'Confort@gmail.com',250114);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983234088','Pollos el Corral','Empresas Pollos el Corral',NULL,'PollosCorral@gmail.com',250115);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983542088','Jannmar','Distribuidora Jannmar.CA',NULL,'Jannmar@gmail.com',250116);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J987742088','Towel','Distribuidora Towel.CA',NULL,'Towel@gmail.com',250117);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J987749088','Industrias Vlelmor','IndustriasVlelmor.CA',NULL,'InstriasVlelmor@gmail.com',250118);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983253088','Nestle','Nestle.CA',NULL,'Nestle@gmail.com',250119);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983259938','Del Mar San Carlos','Del Mar San Carlos.CA',NULL,'Marsancarlos@gmail.com',250120);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J001225398','Inversiones Mueblen','Inversiones Mueblen.org',NULL,'Mueblen.2001@gmail.com',250121);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J000200098','CauchosYa','CauchosYa.org','www.cauchosya.com','cauchosya@gmail.com',250122);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J000100798','Daka','Daka.CA','www.Daka.com','Daka@gmail.com',250123);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J000211298','Mundo Papel','Mundo Papel.org','www.mundopapel2001.com','Mundopapel.2001@gmail.com',250124);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J000345298','Grupo Koren','Grupo Koren.org','www.grupokoren.com','GrupoKoren@gmail.com',250125);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983246191','Cauchos La Plaza','Cauchos La Plaza.S.A.S.', NULL,'CauchosLaPlaza@gmail.com',250126);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983376131','Gemstone Inn','Hotel Gemstone Inn.C.A.','www.hotelgemstoneinn.com/','GemstoneInn@gmail.com',250127);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983506071','XBOS SERVICES','XBOS SERVICES.S.A.','www.xbosservice.es.tl/','XBOSSERVICES@gmail.com',250128);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983636011','Lidotel','Lidotel Centro Lido Caracas.S.A.S.','www.lidotel.com/Venezuela/1/Caracas','Lidotel@gmail.com',250129);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983765951','Instituto Diagnóstico Barcelona','Instituto Diagnóstico Barcelona.S.A.','www.instituto-diagnostico-barcelona.negocio.site/','InstitutoDiagnósticoBarcelona@gmail.com',250130);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J983895891','D&D Inn Tibana','D&D Inn Tibana.S.A.','www.ddinnhotels.com/san-fernando-de-apure/#contactenos','D&DInnTibana@gmail.com',250131);
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('J984025831','Posada Los Nonos','Posada Los Nonos.S.R.L.','www.instagram.com/posadalosnonosc','PosadaLosNonos@gmail.com',250132);








-- por revisar


INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_correo,fk_lugar_fiscal)VALUES ('5','J983245688','Castelo','Castelo.CA','Castelo@gmail.com','32');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_correo,fk_lugar_fiscal)VALUES('6','J983567688','Polar','Empresas Polar.CA','EmpresasPolar@gmail.com','42');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_correo,fk_lugar_fiscal)VALUES('7','J983579088','Confort','Confort.CA','Confort@gmail.com','65');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_correo,fk_lugar_fiscal)VALUES('8','J983234088','Pollos el Corral','Empresas Pollos el Corral','PollosCorral@gmail.com','37');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_correo,fk_lugar_fiscal)VALUES('9','J983542088','Jannmar','Distribuidora Jannmar.CA','Jannmar@gmail.com','53');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_correo,fk_lugar_fiscal)VALUES('10','J987742088','Towel','Distribuidora Towel.CA','Towel@gmail.com','56');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('11','J987749088','Daka','Daka.CA','www.Daka.com','Daka@gmail.com','40');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_correo,fk_lugar_fiscal)VALUES('12','J983253088','Nestle','Nestle.CA','Nestle@gmail.com','40');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_correo,fk_lugar_fiscal)VALUES('13','J983259938','Del Mar San Carlos','Del Mar San Carlos.CA','Marsancarlos@gmail.com','38');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('14','J001225398','Mundo Papel','Mundo Papel.org','www.mundopapel2001.com','Mundopapel.2001@gmail.com','32');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('15','J000200098','Grupo Koren','Grupo Koren.org','www.grupokoren.com','GrupoKoren.2001@gmail.com','32');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_correo,fk_lugar_fiscal)VALUES('16','J000100798','Inversiones Mueblen','Inversiones Mueblen.org','Mueblen.2001@gmail.com','32');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_pagina_web,po_correo,fk_lugar_fiscal)VALUES('17','J000211298','CauchosYa','CauchosYa.org','www.cauchosya.com','cauchosya@gmail.com','33');
INSERT INTO proveedor (po_rif,po_den_comercial,po_razon_social,po_correo,fk_lugar_fiscal)VALUES('18','J000345298','Insdustrias Vlelmor','Insdustrias Vlelmor.CA','InstriasVlelmor@gmail.com','53');
);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J110042212','Imágenes Médicas Carúpano.C.A',NULL,'IMEDICA',NULL,43);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J114278877','El Rincon Del Sabor de Petare.S.A.S.',NULL,'El Roncón Del Sabor',NULL,33);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J116800325','Restaurant Alto.C.A.','https://www.instagram.com/restaurantalto/','Alto Restaurant','https://www.instagram.com/restaurantalto/',32);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J139499191','Viacasa Automercados.C.A.','http://www.viacasa.com/','Viacasa','http://www.viacasa.com/',36);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J147257784','Hesperia WTC Valencia.C.A.','https://www.hoteleshesperia.com.ve/hotel/hesperia-wtc-valencia','WTC Valencia','https://www.hoteleshesperia.com.ve/hotel/hesperia-wtc-valencia',35);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J147680336','Pizzería Restaurant la Guacamaya.S.R.L.',NULL,'La Guacamaya',NULL,33);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J154778462','Lidotel Centro Lido Caracas.S.A.S.','http://www.lidotel.com/Venezuela/1/Caracas','Lidotel','http://www.lidotel.com/Venezuela/1/Caracas',32);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J161434617','Viacasa Automercados.C.A.','http://www.viacasa.com/','Viacasa','http://www.viacasa.com/',36);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J171734659','HOTEL SIRACUSA.S.A.','https://hotel-siracusa-hotel.negocio.site/','HOTEL SIRACUSA','https://hotel-siracusa-hotel.negocio.site/',56);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J223222104','Centro Médico.S.A.','http://www.mlc.com.ve/','Centro Médico MLC','http://www.mlc.com.ve/',55);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J228319657','Mixtos Apure C.A.','https://www.facebook.com/mixtos.apure?fref=ts','Mixtos Apure','https://www.facebook.com/mixtos.apure?fref=ts',51);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J235121809','Automercado & Panaderia La Marina.S.A.S.',NULL,' Automercado La Marina',NULL,36);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J237795049','CLINICA LOS ANDES LTDA.C.A.','http://clinicalosandes.co/','CLINICA LOS ANDES LTDA','http://clinicalosandes.co/',59);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J259324782','Prolicor ANTÍMANO III.S.R.L.',NULL,'Prolicor ANTÍMANO III',NULL,34);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J272744426','Executive Suites Valencia.S.A.S.','https://executivesuites.com.ve/','Executive Suites','https://executivesuites.com.ve/',35);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J288296887','Inversiones Romérsica.C.A.','http://romersica.co.nf/','Inversiones Romérsica','http://romersica.co.nf/',47);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J291651981','Posada la Villa de Jesus.S.A.','http://morrocoy.travel/es/reserva-ya/viewproperty/Posada%20Villa%20de%20Jesus/140','Posada la Villa de Jesus','http://morrocoy.travel/es/reserva-ya/viewproperty/Posada%20Villa%20de%20Jesus/140',57);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J294669246','Cauchos La Plaza.S.A.S.',NULL,'Cauchos La Plaza',NULL,36);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J298172875','Hotel Gemstone Inn.C.A.','http://www.hotelgemstoneinn.com/','Gemstone Inn','http://www.hotelgemstoneinn.com/',44);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J304448980','XBOS SERVICES.S.A.','http://www.xbosservice.es.tl/','XBOS SERVICES','http://www.xbosservice.es.tl/',56);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J324380654','Lidotel Centro Lido Caracas.S.A.S.','http://www.lidotel.com/Venezuela/1/Caracas','Lidotel','http://www.lidotel.com/Venezuela/1/Caracas',32);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J346643224','Instituto Diagnóstico Barcelona.S.A.','https://instituto-diagnostico-barcelona.negocio.site/','Instituto Diagnóstico Barcelona','https://instituto-diagnostico-barcelona.negocio.site/',58);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J352605361','D&D Inn Tibana.S.A.','http://ddinnhotels.com/san-fernando-de-apure/#contactenos','D&D Inn Tibana','http://ddinnhotels.com/san-fernando-de-apure/#contactenos',51);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J362281937','Posada Los Nonos.S.R.L.','https://www.instagram.com/posadalosnonosc','Posada Los Nonos','https://www.instagram.com/posadalosnonosc',45);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J366035108','Hotel Cima.S.A.','http://www.hotelcima.com/','Hotel Cima','http://www.hotelcima.com/',54);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J402955294','CENTRO MATERNO PROCREAR.S.A.','https://www.facebook.com/cmprocrear','PROCREAR','https://www.facebook.com/cmprocrear',41);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J438712012','Clinica Dental El Puerto.S.A.','https://www.facebook.com/clinicadental.elpuerto','Clinica Dental El Puerto','https://www.facebook.com/clinicadental.elpuerto',38);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J439637828','Meliá Caracas.C.A.','https://www.melia.com/en/hotels/venezuela/caracas/gran-melia-caracas/index.htm','Meliá Caracas','https://www.melia.com/en/hotels/venezuela/caracas/gran-melia-caracas/index.htm',33);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J452218040',' Hospital General Dr. José Ignacio Baldó.C.A.',NULL,' Hospital El Algodonal',NULL,34);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J469069554','Executive Suites Valencia.S.A.S.','https://executivesuites.com.ve/','Executive Suites','https://executivesuites.com.ve/',35);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J471727135','Centro MediAlfa','https://www.instagram.com/centromedialfa/?hl=es','MediAlfa','https://www.instagram.com/centromedialfa/?hl=es',32);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J472443997','Hotel Eurobuilding.C.A.','http://www.hoteleuro.com/','Eurobuilding','http://www.hoteleuro.com/',33);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J483103731','Supermercado Hong Kong.S.A.','http://www.supermercadohongkong.com/','Supermercado Hong Kong','http://www.supermercadohongkong.com/',47);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J490135632','Lidotel Hotel Boutique Barquisimeto.C.A.','https://www.lidotel.com/Venezuela/3/Barquisimeto','Lidotel Boutique Barquisimeto','https://www.lidotel.com/Venezuela/3/Barquisimeto',40);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J492479697','Supermercado Central Madeirense.S.A.','http://www.centralmadeirense.com.ve/','Central Madeirense','http://www.centralmadeirense.com.ve/',37);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J529510113','Centro Clínico Materno Pediátrico Zulia.S.R.L.','http://clinicazulia.com/','Materno Pediátrico Zulia','http://clinicazulia.com/',36);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J535687524','Bocadito Express.S.A.','https://www.bocadito.express/','Bocadito Express','https://www.bocadito.express/',46);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J554877060','Amaranto.S.A.','https://www.amarantomgta.com/','Amaranto','https://www.amarantomgta.com/',46);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J564696540','GoodYear.C.A.','http://www.goodyear.com.ve/','GoodYear','http://www.goodyear.com.ve/',48);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J601356966','AMBULATORIO DE MAIQUETIA.S.A.S.',NULL,'AMBULATORIO MAIQUETIA',NULL,38);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J612885638','Clinica La Sagrada Familia.C.A.','http://www.lasagrada.com.ve/','Clinica Sagrada Familia','http://www.lasagrada.com.ve/',36);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J625393868','Talleres VIRGINIAS CAKES.S.R.L.',NULL,'VIRGINIAS CAKES',NULL,39);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J630894437','Clínica Los Próceres C.A.','http://clinica-los-proceres-ca.business.site/','Clínica Los Próceres','http://clinica-los-proceres-ca.business.site/',48);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J648529850','Pizzería Restaurant la Guacamaya.S.R.L.',NULL,'La Guacamaya',NULL,33);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J659273592','Automercado & Panaderia La Marina.S.A.S.',NULL,' Automercado La Marina',NULL,36);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J668494501','Living Hotel.C.A.','http://www.hotelier.net.ve/hoteles/living-hotel/','Living Hotel','http://www.hotelier.net.ve/hoteles/living-hotel/',54);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J675261630','Centro MediAlfa','https://www.instagram.com/centromedialfa/?hl=es','MediAlfa','https://www.instagram.com/centromedialfa/?hl=es',32);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J680621200','FISIOTERAPIA BEATRIZ MALDONADO.S.A.','https://consultorio-de-fisioterapia-beatriz.negocio.site/','FISIOTERAPIA BEATRIZ MALDONADO','https://consultorio-de-fisioterapia-beatriz.negocio.site/',59);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J719171238','Clínica La Esperanza.S.A.','http://www.clinicalaesperanza.com/','Clínica La Esperanza','http://www.clinicalaesperanza.com/',41);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J719381085','Centro Clinico Los Olivos.S.A.S.','http://cclo.com.ve/','Centro Clinico Los Olivos','http://cclo.com.ve/',36);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J725532390','Hesperia WTC Valencia.C.A.','https://www.hoteleshesperia.com.ve/hotel/hesperia-wtc-valencia','WTC Valencia','https://www.hoteleshesperia.com.ve/hotel/hesperia-wtc-valencia',35);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J742257059','Panaderia Don Manteka.S.A.',NULL,'Don Manteka',NULL,43);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J752332978','Policlinica Especialidades.S.A.','https://policlinica-especialidades.negocio.site/','Policlinica Especialidades','https://policlinica-especialidades.negocio.site/',52);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J753179559','Clinica La Sagrada Familia.C.A.','http://www.lasagrada.com.ve/','Clinica Sagrada Familia','http://www.lasagrada.com.ve/',36);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J793645499','Unidad De Atención Respiratoria Respisalud CA','http://www.respisaludca.wixsite.com/respisalud','Respisalud','http://www.respisaludca.wixsite.com/respisalud',55);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J799800422','Centro Clinico Los Olivos.S.A.S.','http://cclo.com.ve/','Centro Clinico Los Olivos','http://cclo.com.ve/',36);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J799904591','Supermercado Luxor.S.A.S.','http://www.supermercadoluxor.com/','Supermercado Luxor','http://www.supermercadoluxor.com/',37);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J804093980','CEMNCA.C.A.','https://centro-de-especialidades-medicas-neveri-cemnca.negocio.site/','Especialidades Médicas Neverí','https://centro-de-especialidades-medicas-neveri-cemnca.negocio.site/',58);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J810797583','Cauchos La Plaza.S.A.S.',NULL,'Cauchos La Plaza',NULL,36);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J820763335','Restaurant Alto.C.A.','https://www.instagram.com/restaurantalto/','Alto Restaurant','https://www.instagram.com/restaurantalto/',32);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J826453205','Centro Clínico Materno Pediátrico Zulia.S.R.L.','http://clinicazulia.com/','Materno Pediátrico Zulia','http://clinicazulia.com/',36);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J842961567','díadía Soublette.S.R.L.','http://www.diadia.com.ve/','díadía Av. Soublette','http://www.diadia.com.ve/',39);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J843722188','Prolicor ANTÍMANO III.S.R.L.',NULL,'Prolicor ANTÍMANO III',NULL,34);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J846784790','Meliá Caracas.C.A.','https://www.melia.com/en/hotels/venezuela/caracas/gran-melia-caracas/','Meliá Caracas','https://www.melia.com/en/hotels/venezuela/caracas/gran-melia-caracas/',33);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J848807368','Complejo Turístico Mis Ensueños.C.A.','https://tierradegracia.net/hospedaje/hoteles-posadas-trujillo/complejo-turistico-mis-ensuenos','Mis Ensueños','https://tierradegracia.net/hospedaje/hoteles-posadas-trujillo/complejo-turistico-mis-ensuenos',49);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J850318981','Marina Puerto Varadero Yacht Club.C.A.','https://marinapuertovaradero.com/','Puerto Varadero Yacht Club','https://marinapuertovaradero.com/',57);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J866221424','TenientePizza.S.A.','http://www.instagram.com/TenientePizza','TenientePizza','http://www.instagram.com/TenientePizza',53);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J869076112',' Hospital General Dr. José Ignacio Baldó.C.A.',NULL,' Hospital El Algodonal',NULL,34);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J869943838','Hotel Eurobuilding.C.A.','http://www.hoteleuro.com/','Eurobuilding','http://www.hoteleuro.com/',33);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J877238625','Eurobuilding Express El Tigre.C.A.','http://hoteleuro.com/','Eurobuilding El Tigre','http://hoteleuro.com/',44);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J892345614','CLINICA DENTAL ODONTO.S.A.','https://www.instagram.com/clinicadentalodonto/','CLINICA DENTAL ODONTO','https://www.instagram.com/clinicadentalodonto/',52);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J901416205','Dolce And Bake.S.A.','http://www.instagram.com/dolceandbake','Dolce And Bake','http://www.instagram.com/dolceandbake',50);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J912575600','Sibana´s S.A.','http://www.facebook.com/Sibanas','Dolce And Bake','http://www.facebook.com/Sibanas',53);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J935562160','Pueblo Tantodi.S.A.','http://www.tantodi.com.ve/','Pueblo Tantodi','http://www.tantodi.com.ve/',49);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J951072825','Everfit.S.A.S.','https://everfit-sportswear-store.negocio.site/','Everfit','https://everfit-sportswear-store.negocio.site/',42);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J967032665','Inversiones Condomania C.A.','http://www.condomaniaplus.com.ve/','Condomania','http://www.condomaniaplus.com.ve/',42);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J974759133','Hotel Pirineos.S.R.L.','http://www.hotelpirineos.com.ve/','Hotel Pirineos','http://www.hotelpirineos.com.ve/',45);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J976927260','Hostería El Obelisco.S.R.L.','http://hosteriaobelisco.com.ve/','Hostería El Obelisco','http://hosteriaobelisco.com.ve/',40);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J982995642','NAFU.S.A.','http://www.instagram.com/nafurestaurant','NAFU','http://www.instagram.com/nafurestaurant',50);
INSERT INTO proveedor(po_rif,po_razon_social,po_pagina_web,po_den_comercial,po_correo,fk_lugar_fiscal)VALUES('J999308074','El Rincon Del Sabor de Petare.S.A.S.',NULL,'El Roncón Del Sabor',NULL,33);
