


INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - El Cafetal',250122);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Petare',250123);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Antímano',250124);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Valencia',250125);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Maracaibo',250126);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Maracay',250127);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - La Guaira',250128);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Maiquetía',250129);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Barquisimeto',250120);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Puerto Ordaz',250121);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Puerto La Cruz',250122);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Carúpano',250123);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - El Tigre',250124);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Cristóbal',250125);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Margarita',250126);    
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Coro',250127);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Guanare',250128);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Trujillo',250129);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Mérida',250120);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Fernando de Apure',250121);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Paraguaná',250122);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Los Teques',250123);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Barinas',250124);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Valle la Pascua',250125);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Anaco',250126);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Tucacas',250127);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Barcelona',250128);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Ureña',250129);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Casimiro',250120);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Guanta',250121);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Costa Oriental del Lago',250122);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Ciudad Bolívar',250123);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Félix',250124);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Antonio de los Altos',250125);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Ciudad Ojeda',250126);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Carora',250127);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Acarigua',250128);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - La Victoria',250129);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Villa de Cura',250120);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Táriba',250121);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Puerto Ayacucho',250122);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Fernando de Atabapo',250123);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Biruaca',250124);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Barrancas',250125);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Naguanagua',250126);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Tinaquillo',250127);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Girardot',250128);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Tucupita',250129);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Casacoima',250120);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - El Junquito',250121);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Chaguaramas',250122);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - El Ámparo',250123);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Caripe',250124);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Quiriquire',250125);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Pampatar',250126);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Yaguaraparo',250127);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - La Puerta',250128);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Felipe',250129);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Chivacoa',250120);