

INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - El Cafetal',250449);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Petare',250450);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Antímano',250451);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Valencia',250452);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Maracaibo',250453);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Maracay',250454);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - La Guaira',250455);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Maiquetía',250456);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Barquisimeto',250457);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Puerto Ordaz',250458);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Puerto La Cruz',250459);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Carúpano',250460);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - El Tigre',250461);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Cristóbal',250462);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Margarita',250463);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Coro',250464);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Guanare',250465);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Trujillo',250466);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Mérida',250467);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Fernando de Apure',250468);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Paraguaná',250469);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Los Teques',250470);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Barinas',250471);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Valle la Pascua',250472);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Anaco',250473);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Tucacas',250474);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Barcelona',250475);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Ureña',250476);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Casimiro',250477);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Guanta',250478);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Costa Oriental del Lago',250479);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Ciudad Bolívar',250480);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Félix',250481);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Antonio de los Altos',250482);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Ciudad Ojeda',250483);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Carora',250484);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Acarigua',250485);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - La Victoria',250486);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Villa de Cura',250487);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Táriba',250488);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Puerto Ayacucho',250489);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Fernando de Atabapo',250490);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Biruaca',250491);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Barrancas',250492);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Naguanagua',250493);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Tinaquillo',250494);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Girardot',250495);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Tucupita',250496);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Casacoima',250497);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - El Junquito',250498);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Chaguaramas',250499);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - El Ámparo',250500);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Caripe',250501);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Quiriquire',250502);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Pampatar',250503);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Yaguaraparo',250504);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - La Puerta',250505);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Felipe',250506);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Chivacoa',250507);

