INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - El Cafetal',32);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Petare',33);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Antímano',34);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Valencia',35);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Maracaibo',36);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Maracay',37);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - La Guaira',38);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Maiquetía',39);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Barquisimeto',40);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Puerto Ordaz',41);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Puerto La Cruz',42);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Carúpano',43);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - El Tigre',44);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Cristóbal',45);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Margarita',46);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Coro',47);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Guanare',48);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Trujillo',49);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Mérida',50);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Fernando de Apure',51);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Paraguaná',52);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Los Teques',53);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Barinas',54);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Valle la Pascua',55);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Anaco',56);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Tucacas',57);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Barcelona',58);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Ureña',59);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Casimiro',60);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Guanta',61);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Costa Oriental del Lago',62);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Ciudad Bolívar',63);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Félix',64);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Antonio de los Altos',65);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Ciudad Ojeda',66);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Carora',67);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Acarigua',68);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - La Victoria',69);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Villa de Cura',70);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Táriba',71);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Puerto Ayacucho',72);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Fernando de Atabapo',73);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Biruaca',74);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Barrancas',75);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Naguanagua',76);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Tinaquillo',77);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Girardot',78);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Tucupita',79);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Casacoima',80);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - El Junquito',81);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Chaguaramas',82);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - El Ámparo',83);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Caripe',84);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Quiriquire',85);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Pampatar',86);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Yaguaraparo',87);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - La Puerta',88);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - San Felipe',89);
INSERT INTO tienda (ti_nombre, fk_lugar) VALUES ('UCABmart - Chivacoa',90);